# Generated by Django 4.2.7 on 2023-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsform',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detailsform',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
